blank_issues_enabled: true
contact_links:
  - name: Help
    url: ""
    about: Please join our Discord server for help using AiAdmin
  - name: Troubleshooting
    url: https://github.com/AllSage/AiAdmin/blob/main/docs/faq.md#faq
    about: See the FAQ for common issues and solutions
